### ISSUE TITLE
lib/adm.js leaks ZK clients

### ISSUE THREAD

**Issue by AmlingPalantir** [joyent/manatee#12]
For complex reasons we're using adm.js in a longer lived context and so it leaking connections is actually of interest to us.  My analysis of the problem is that createZkClient leaks the connection if it successfully connects, but takes longer than 10s.  The logging I had to back this up showed repeatedly it hitting the timeout callback and then the connection callback for the same original call of createZkClient.  The number of times this had happened matched 1:1 with the number of [apparently leaked] ESTABLISHED connections to ZK in periods of idleness.

**Comment by davepacheco** [comment]
That analysis makes sense.  Sorry for the issue.

**Comment by davepacheco** [comment]
I'm really sorry this took so long to merge.  I've just integrated it.  I reformatted the commit comment to match our conventions -- I hope you don't mind.
