### ISSUE TITLE
Various wrong paths and typos

### ISSUE THREAD

**Issue by sperreault** [joyent/manatee#7]
Wrong smf state in backupserver.xml
Wrong default log dir in postgresql.conf
Wrong default dataDir in sitter.json

**Comment by davepacheco** [comment]
Thanks for this.  The sitter.json and postgresql.conf files are correct for our deployments.  They should be treated as templates that may need to be customized for different environments.

The SMF manifest file is definitely broken.  I've fixed that with 8fb54fa0cc90d8eb254ea2c151c853d2eb5378bc, and I've also incorporated the Makefile snippets from eng.git that will cause such issues to fail "make check" in the future.  Thanks for pointing this out.  (For the curious, the reason this doesn't break our existing deployments is that we don't use these manifests.  We use manifests built in the manta-manatee and sdc-manatee repos, which wrap manatee for use in Manta and SDC, respectively.)
