### ISSUE TITLE
node-gyp fails to rebuild

### ISSUE THREAD

**Issue by jamesdwilson** [joyent/manatee#9]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'manatee@0.2.1' ]
2 info using npm@1.3.22
3 info using node@v0.11.10
4 verbose node symlink /usr/bin/node
5 verbose cache add [ 'manatee@0.2.1', null ]
6 verbose cache add name=undefined spec="manatee@0.2.1" args=["manatee@0.2.1",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'manatee@0.2.1',
7 verbose parsed url   path: 'manatee@0.2.1',
7 verbose parsed url   href: 'manatee@0.2.1' }
8 verbose cache add name="manatee" spec="0.2.1" args=["manatee","0.2.1"]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: '0.2.1',
9 verbose parsed url   path: '0.2.1',
9 verbose parsed url   href: '0.2.1' }
10 verbose addNamed [ 'manatee', '0.2.1' ]
11 verbose addNamed [ '0.2.1', '0.2.1' ]
12 silly lockFile 4a54bef6-manatee-0-2-1 manatee@0.2.1
13 verbose lock manatee@0.2.1 /home/james/.npm/4a54bef6-manatee-0-2-1.lock
14 verbose url raw manatee/0.2.1
15 verbose url resolving [ 'https://registry.npmjs.org/', './manatee/0.2.1' ]
16 verbose url resolved https://registry.npmjs.org/manatee/0.2.1
17 info trying registry request attempt 1 at 15:11:39
18 verbose etag "DS3TCVBFA08QAEUTCFXD4GF0B"
19 http GET https://registry.npmjs.org/manatee/0.2.1
20 http 304 https://registry.npmjs.org/manatee/0.2.1
21 silly registry.get cb [ 304,
21 silly registry.get   { date: 'Sat, 28 Feb 2015 21:11:41 GMT',
21 silly registry.get     server: 'Apache',
21 silly registry.get     via: '1.1 varnish',
21 silly registry.get     'last-modified': 'Sat, 28 Feb 2015 21:11:42 GMT',
21 silly registry.get     'cache-control': 'max-age=60',
21 silly registry.get     etag: '"DS3TCVBFA08QAEUTCFXD4GF0B"',
21 silly registry.get     age: '0',
21 silly registry.get     'x-served-by': 'cache-dfw1826-DFW',
21 silly registry.get     'x-cache': 'MISS',
21 silly registry.get     'x-cache-hits': '0',
21 silly registry.get     'x-timer': 'S1425157901.996789,VS0,VE62',
21 silly registry.get     vary: 'Accept',
21 silly registry.get     'content-length': '0',
21 silly registry.get     connection: 'close' } ]
22 verbose etag manatee/0.2.1 from cache
23 silly lockFile 4a54bef6-manatee-0-2-1 manatee@0.2.1
24 silly lockFile 4a54bef6-manatee-0-2-1 manatee@0.2.1
25 silly resolved [ { name: 'manatee',
25 silly resolved     version: '0.2.1',
25 silly resolved     description: 'A node.js wrapper for the Manatee barcode library',
25 silly resolved     main: 'index.js',
25 silly resolved     scripts:
25 silly resolved      { test: 'echo "Error: no test specified" && exit 1',
25 silly resolved        install: 'node-gyp rebuild' },
25 silly resolved     repository:
25 silly resolved      { type: 'git',
25 silly resolved        url: 'git://github.com/lamassu/node-manatee.git' },
25 silly resolved     keywords: [ 'pdf417' ],
25 silly resolved     author:
25 silly resolved      { name: 'Josh Harvey',
25 silly resolved        email: 'josh@lamassu.is',
25 silly resolved        url: 'https://lamassu.is/' },
25 silly resolved     license: 'UNLICENSE',
25 silly resolved     gypfile: true,
25 silly resolved     bugs: { url: 'https://github.com/lamassu/node-manatee/issues' },
25 silly resolved     readme: '# node-manatee\n\nA node.js wrapper for the Manatee barcode library\n\n# Build instructions\n\n1. Copy your libBarcodeScanner.a or libBarcodeScanner.so library from Manatee\nto your system library directory (e.g., /usr/local/lib).\n(You can get a demo version for free by signing up on their site.)\n2. ```node-gyp configure```\n3. ```node-gyp build```\n',
25 silly resolved     readmeFilename: 'README.md',
25 silly resolved     homepage: 'https://github.com/lamassu/node-manatee',
25 silly resolved     _id: 'manatee@0.2.1',
25 silly resolved     _from: 'manatee@0.2.1' } ]
26 info install manatee@0.2.1 into /usr/lib
27 info installOne manatee@0.2.1
28 info /usr/lib/node_modules/manatee unbuild
29 verbose tar unpack /home/james/.npm/manatee/0.2.1/package.tgz
30 silly lockFile cd883a82-tar-usr-lib-node-modules-manatee tar:///usr/lib/node_modules/manatee
31 verbose lock tar:///usr/lib/node_modules/manatee /home/james/.npm/cd883a82-tar-usr-lib-node-modules-manatee.lock
32 silly lockFile 34f5c29a-es-npm-manatee-0-2-1-package-tgz tar:///home/james/.npm/manatee/0.2.1/package.tgz
33 verbose lock tar:///home/james/.npm/manatee/0.2.1/package.tgz /home/james/.npm/34f5c29a-es-npm-manatee-0-2-1-package-tgz.lock
34 silly gunzTarPerm modes [ '755', '644' ]
35 silly gunzTarPerm extractEntry package.json
36 silly gunzTarPerm extractEntry .npmignore
37 silly gunzTarPerm extractEntry README.md
38 silly gunzTarPerm extractEntry index.js
39 silly gunzTarPerm extractEntry .jshintrc
40 silly gunzTarPerm extractEntry UNLICENSE
41 silly gunzTarPerm extractEntry binding.gyp
42 silly gunzTarPerm extractEntry build/Makefile
43 silly gunzTarPerm extractEntry build/binding.Makefile
44 silly gunzTarPerm extractEntry build/config.gypi
45 silly gunzTarPerm extractEntry build/gyp-mac-tool
46 silly gunzTarPerm extractEntry build/manatee.target.mk
47 silly gunzTarPerm extractEntry src/BarcodeScanner.h
48 silly gunzTarPerm extractEntry src/manatee.cc
49 silly lockFile cd883a82-tar-usr-lib-node-modules-manatee tar:///usr/lib/node_modules/manatee
50 silly lockFile cd883a82-tar-usr-lib-node-modules-manatee tar:///usr/lib/node_modules/manatee
51 silly lockFile 34f5c29a-es-npm-manatee-0-2-1-package-tgz tar:///home/james/.npm/manatee/0.2.1/package.tgz
52 silly lockFile 34f5c29a-es-npm-manatee-0-2-1-package-tgz tar:///home/james/.npm/manatee/0.2.1/package.tgz
53 info preinstall manatee@0.2.1
54 verbose readDependencies using package.json deps
55 verbose readDependencies using package.json deps
56 silly resolved []
57 verbose about to build /usr/lib/node_modules/manatee
58 info build /usr/lib/node_modules/manatee
59 verbose linkStuff [ true, '/usr/lib/node_modules', true, '/usr/lib/node_modules' ]
60 info linkStuff manatee@0.2.1
61 verbose linkBins manatee@0.2.1
62 verbose linkMans manatee@0.2.1
63 verbose rebuildBundles manatee@0.2.1
64 info install manatee@0.2.1
65 verbose unsafe-perm in lifecycle false
66 info manatee@0.2.1 Failed to exec install script
67 info /usr/lib/node_modules/manatee unbuild
68 info preuninstall manatee@0.2.1
69 info uninstall manatee@0.2.1
70 verbose true,/usr/lib/node_modules,/usr/lib/node_modules unbuild manatee@0.2.1
71 info postuninstall manatee@0.2.1
72 error manatee@0.2.1 install: `node-gyp rebuild`
72 error Exit status 1
73 error Failed at the manatee@0.2.1 install script.
73 error This is most likely a problem with the manatee package,
73 error not with npm itself.
73 error Tell the author that this fails on your system:
73 error     node-gyp rebuild
73 error You can get their info via:
73 error     npm owner ls manatee
73 error There is likely additional logging output above.
74 error System Linux 3.8.0-35-generic
75 error command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "manatee@0.2.1"
76 error cwd /home/james/projects/lamassu-machine
77 error node -v v0.11.10
78 error npm -v 1.3.22
79 error code ELIFECYCLE
80 verbose exit [ 1, true ]

===
$ node-gyp 

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `make` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates a Makefile for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@1.0.2  /usr/lib/node_modules/node-gyp
node@0.11.10

**Comment by jamesdwilson** [comment]
uname -a
Linux agape 3.8.0-35-generic #50-Ubuntu SMP Tue Dec 3 01:24:59 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by notmatt** [comment]
@jamesdwilson - sorry for any hassle, but it appears there's a name collision here. The npm 'manatee' package looks like it's for reading barcodes, and has nothing to do with this project, which is a mechanism for managing postgres replication and failover.

The 'manatee' published on npm should have bugs filed for it here: [https://github.com/lamassu/node-manatee/issues] (found using `npm info manatee`).

Cheers,
matt.

**Comment by jamesdwilson** [comment]
Thank you! Sorry for the confusion.

On Sat, Feb 28, 2015 at 6:38 PM, Matthew Smillie <notifications@github.com>
wrote:

> @jamesdwilson <https://github.com/jamesdwilson> - sorry for any hassle,
> but it appears there's a name collision here. The npm 'manatee' package
> looks like it's for reading barcodes, and has nothing to do with this
> project, which is a mechanism for managing postgres replication and
> failover.
>
> The 'manatee' published on npm should have bugs filed for it here:
> https://github.com/lamassu/node-manatee/issues.
>
> Cheers,
> matt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joyent/manatee/issues/9#issuecomment-76561221>.
>



-- 
Thank you!
